apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-gen-deployment
  labels:
    app: recipe-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-gen
  template:
    metadata:
      labels:
        app: recipe-gen
    spec:
      containers:
      - name: recipe-gen
        image: gcr.io/b-508911/recipe-gen:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi


